### ISSUE TITLE
ONL installer gets unknown onie_platform in latest ONIE

### ISSUE THREAD

**Issue by david56** [opencomputeproject/OpenNetworkLinux#283]
Hello @carlroth, @jnealtowns , @cbrune ,

In latest ONIE, I had removed machine.conf from the initrd image.  i.e., machine.conf is generated at ONIE run-time dynamically rather than putting a static one in the image.  ONL had been revised to use `onie-sysinfo` on Dec 27 (#280 ). We found ONL install failed  because it unpacks the image to execute `onie-sysinfo` to get `onie_platform`.   In the unpacked environment, machine.conf is not existent so that `onie-sysinfo` will reply `unknown` to ONL installer.  It will try to import a module named `unknown`:

    Traceback (most recent call last):
      File "/usr/bin/onl-install", line 6, in <module>
        import onl.install.App
      File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 21, in <module>
        import ConfUtils, BaseInstall
      File "/usr/lib/python2.7/dist-packages/onl/install/ConfUtils.py", line 14, in <module>
        from onl.sysconfig import sysconfig
      File "/usr/lib/python2.7/dist-packages/onl/sysconfig/__init__.py", line 13, in <module>
        from onl.platform.current import OnlPlatform
      File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 62, in <module>
        OnlPlatform = import_subsystem_platform_class()
      File "/usr/lib/python2.7/dist-packages/onl/platform/current.py", line 57, in import_subsystem_platform_class
        m = importlib.import_module('%s.platform.%s' % (subsystem, platform_module))
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named unknown
    Install failed.

It looks that it is necessary to keep machine.conf in the image to make the installer go smoothly.  But `onie-sysinfo` still lacks machine-live.conf (which is also generated dynamically at ONIE run-time) for calculating the *real* `onie_platform`.  We need to discuss how to fix the issue.

I would appreciate your opinions.  Thank you very much.

Cheers,
David

**Comment by david56** [comment]
I did a test on AS7712_32X having a revised ONIE keeping machine.conf in the initrd image which can install latest ONL normally.

**Comment by jnealtowns** [comment]
@david56 
The existing design was a convenience since the installer itself runs as part of the Loader initrd in multiple envirnonments. But it isn't necessary (especially if it no longer works). 

@carlroth Lets modify the platform detection logic to remove the chroot into ONIE. 
This means the platform id must be passed as a configuration parameter to the installer prior to entering the Loader initrd instead of the installer detecting it itself. 

# Environment override
1. if $ONL_INSTALL_PLATFORM then echo "platform=$ONL_INSTALL_PLATFORM" >> installer.conf

# Installing from ONIE
2. If ONIE: echo "platform=`onie-sysinfo -p` >> installer.conf

# Installing form ONL
3. If ONL : echo "platform=$(cat /etc/onl/platform)" >> installer.conf
etc. 

What do you think?

cc @cbrune

**Comment by carlroth** [comment]
see https://github.com/opencomputeproject/OpenNetworkLinux/pull/287

**Comment by david56** [comment]
The latest ONL can be installed via latest ONIE normally now.  Thank you.
