### ISSUE TITLE
Accton ONLP library bug

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#359]
Inside the library (fani.c) is the function  which takes info from the filesystem and fills the structure. In Accton case:
https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/accton/x86-64/x86-64-accton-as7312-54xs/onlp/builds/src/module/src/fani.c

Fan tray of Accton platform has two fans - front and rear. 
First – front fan speed is read and set to the element  "rpm " of structure onlp_fan_info_t (lines 135 – 144)
Then rear fans speed is read and assigned TO THE SAME field of the structure overwriting front fan speed if rear fan is slower (lines 146-160).

As a result, my calling function is getting only one value, whichever is smaller – front or rear – undetermined.
For me it is not acceptable. A would like Accton to make a fix.
 
Since onlp_fan_info_t is generic and cannot be changed I suggest that Accton library uses 12 fans objects with unique object id’s  instead of 6 they currently have. Two objects for one single fan tray, one for the front fan in a tray, another for the rear fan.

**Comment by brandonchuang** [comment]
It is our current design, it is not a bug.
We only take the rpm of the slower fan because we would like to monitor if any fan is working unusual.
If one of front or rear fan is broken, then the whole fan module should be replaced.
When 12 fans are shown in onlpdump, then it would be not so intuitive as current output.
So we prefer to keep 6 fans objects.
