### ISSUE TITLE
ONLP library Fan info - second fan RPM is missing

### ISSUE THREAD

**Issue by Vladimir-NTCT** [opencomputeproject/OpenNetworkLinux#666]
Most of the fan trays used by different vendors have two fans located consecutively. But ONLP API onlp_fan_info_get() fill out a structure onlp_fan_info_t which has rpm value for only one fan.

/**
 * Fan information structure.
 */
typedef struct onlp_fan_info_s {
    /** OID Header */
    onlp_oid_hdr_t hdr;

    /* Status */
    uint32_t status;

    /* Capabilities */
    uint32_t caps;

    **/* Current fan speed, in RPM, if available */
    int rpm;**

    /* Current fan percentage, if available */
    int percentage;

    /* Current fan mode, if available  */
    onlp_fan_mode_t mode;

    /* Model (if applicable) */
    char model[ONLP_CONFIG_INFO_STR_MAX];

    /* Serial Number (if applicable) */
    char serial[ONLP_CONFIG_INFO_STR_MAX];

} onlp_fan_info_t;

Same for fan speed percentage.

Structure has to be modified to include second fan RPM and percentage and vendors libraries have to fill both fans data properly.

**Comment by jnealtowns** [comment]
@Vladimir-NTCT  For better or for worse all platforms currently report fans in each fan tray individually.

**Comment by Vladimir-NTCT** [comment]
> 
> 
> @Vladimir-NTCT For better or for worse all platforms currently report fans in each fan tray individually.

Yes, but one single tray can have (and has) more than one fan.  For example, Accton AS7326-56X has 6 fan trays with two fans in each tray.
![image](https://user-images.githubusercontent.com/38267111/72105484-7bd86b80-32e2-11ea-87f6-0d3eb3e70562.png)

There should be a way for the application software to get enformation about both fans in a tray.

**Comment by jnealtowns** [comment]
@Vladimir-NTCT  I will try to elaborate on my answer. 

It is up to the platform implementation to expose each fan as a separate OID. 

If the platform reports a different OID for each fan in a fan tray (regardless of their number) then you can read the individual status for each fan in the tray. This includes more than the RPM but also the operational status (like only one fan in the tray has failed because someone stuck a toothpick in it). 

If the platform cannot resolve the individual status it will sometimes synthesize the status for both fans based on the fan tray mechanicals and the controller which may be in the tray. Perhaps the status is available but is synthesized in the CPLD and thus beyond the model of the software itself. 

The API allows for all relevant information to be exported. It is the responsibility of the platform implementation to actually export the information where possible.

**Comment by Vladimir-NTCT** [comment]
So, if I understood you correctly Accton ONLP library should report not 6 but 12 objects  ONLP_OID_TYPE_FAN and allow to get onlp_fan_info_s for each of them individually?

**Comment by jnealtowns** [comment]
@Vladimir-NTCT  Yes that is correct.
