### ISSUE TITLE
How to specify a owned x86_64-all.config

### ISSUE THREAD

**Issue by tsihang** [opencomputeproject/OpenNetworkLinux#703]
Hi, there

I am trying to build ONL for a specified device, and later I may  request a pull when all things done.
My question is : how to deal my own change to avoid the conflict with  $ARCH/x86_64-all.config in ONL repository ?

Many Thanks

**Comment by sonoble** [comment]
There are a few ways to do this, but most will not survive an update to the ONL repository that affects the kernels.  Most every kernel past 3.16 is still in long term support, so they may get updated for bug/security fixes, but you can always put your config back in after.  I would suggest you keep a copy of your kernel config outside of ONL so that you have it available.  You can also change the name of the kernel config in the Makefile and PKG.yml for the arch kernel, but that requires that you manage files that you are not used to managing.

**Comment by tsihang** [comment]
Hi @sonoble  it helps me a lot.
Many thanks
